language: cpp
compiler:
- gcc
- clang
env:
  global:
  - APT_DEPENDENCIES="doxygen doxygen-latex libltdl-dev libboost-all-dev liblog4cxx10-dev libeigen3-dev"
  - GIT_DEPENDENCIES="roboptim/roboptim-core"
  - DEBSIGN_KEYID=5AE5CD75
  - PPA_URI="roboptim/ppa"
  - NSIQCPPSTYLE_FILEFILTERPATH=cmake/filefilter.txt
  - GH_USERNAME=thomas-moulard
  - GH_REPO=roboptim/roboptim-core-plugin-nag
  - ALLOW_TESTSUITE_FAILURE=true
  - secure: jlN/+P8C3DXiowQsGF46AlDRi4jtUjj+ELt4AUQUV20PjNA8Z8QfJbwiXqdZKMMshRowz1uneQ9h0UIItuoAiPYOECqga0jjEgSFKgvBpe371W3agH1cHoepIPgXEcaPDBM40PlaSpXLmxyEFVvCsUjTjrHfu+VDXUjH7+gSjg0=
  - secure: eOFrmE1op6o+lFhiGDdSMYL+f2hoTof/sxUI5uv6sWILk4QEbSrP6zKc7CQdqAgBLHfXp8YqPyTAP3RPL9fTHT7o/6/KqHyEr+TaYNvZODCQeWkMW4wIZ1NxB+1eZMDtjZfeKTV5NwfGWqldA9dyLhi+6PtznS4QsjUTH0/5Ji0=
  - secure: ekJ2WUgLkygFwmHlSrkS0H3y1qnwBCZY/T16EOi2VYs9+5ARy19YnNhdm27Rf36lrL8laJeJ+djsh36RNiaZzgDjUUBIDcE35NLvj1f3850bhyM7rzACD+WI5cqoAsMGpzvjF6KTZMPMFWdcNXLrZPM/VHtTFRaTrNa5uZiGV/Q=
notifications:
  hipchat:
    rooms:
      secure: T6qgryodSDzE/22d7zReGPj3nTNNgv2gyTwtjI0SBcnGULuSMBwsiijyYICBJBkmmBYM3aYDvhivyHOy1k53/9jVfWU8bRSzbyzKumV63K9mY5Oq5UneKbggPfwFe0aE9qyL2M9tovUgZepS+VRjk6ghmS0DtmqvtTabhnk9aEA=
  email: roboptim@googlegroups.com
before_install:
- ./.travis/dependencies/eigen-3.2.0
- ./.travis/dependencies/nag
- ./.travis/run  before_install
script:
- . .travis/common.sh; export CMAKE_ADDITIONAL_OPTIONS="-DNAG_DIR=\"$install_dir/NAG/cll6a23dhl\""; export LD_LIBRARY_PATH="$install_dir/NAG/cll6a23dhl/lib:$LD_LIBRARY_PATH"; ./.travis/run build
after_failure: ./.travis/run after_failure
after_success: ./.travis/run after_success
branches:
  only:
  - master
  - debian
matrix:
  allow_failures:
  - compiler: clang
