sudo: required
language: cpp
env:
  global:
    - secure: "cz8Eo/xP13SCH6j38LE4eFqAfI7H5BUQaWaK9yObZWYxCm3M6FL6TOUJ0vecwKJoPyUuk5Z9qYwZCZstkID5Vyn1xNm5PavdZcRhhb7E9knJeBSTMLAqn51I8KL64E0lyqvqgM89knotGvjgY+HshwWYmR+f9v/sbFyVoUvBvvo="
    - secure: "F9mibfsT3Ezk0RRsgOHy8RUO82H05REGmJKLDKdHiHE3toxykQX64oNBB8txjHoi+UF0H1Gwmk4oB/pNeILtyHdSuB7hB1Muod9wspOuKrzO7SMTGdjpPw7nDjQEmtfrZFhXEGb/3xm66uSGojhwe0RJF5mOzyfno+G8SIJyos4="
    - secure: "Hn0mNkHgP0azydZUqq3CXifrDw+6adcJ541/EInw59BhM9Q7orJEDsfkqSMICLsIQxe+qNb0pYjCze10GZQPqhNBKcsDGmMDOqvwNPyOqEy8TOWl0j6emO3K0QVbfz7l2I9Gvwym/ZVQ+4XH1oZgmfJOPgxLmWZ69wZUDFBlMCg="
    - secure: "Atmvwjxe3WqmUPumdDubBTvgC1v5JbIVtgBwuvZOsYdQ36eKOCSBuS0uVS0WbHHmeljeVUzb1EEGitKKjS6hYAkdg3F5eFmHPophL8zUHkY4fGAE80oGyPAFOeqZzIYp5cpStR8540K32C7vkqKqPFkufwLGKI0QZ87HP3U60AM="
    - APT_DEPENDENCIES="doxygen libltdl-dev libboost-all-dev liblog4cxx10-dev"
    - HOMEBREW_DEPENDENCIES="doxygen log4cxx"
    - GIT_DEPENDENCIES=""
    - GH_USERNAME=bchretien
    - GH_REPO=roboptim/roboptim-core
    - DEBSIGN_KEYID=5AE5CD75
    - PPA_URI="roboptim/ppa"
    - LCOV_IGNORE_RULES="*tests*"
notifications:
  hipchat:
    rooms:
      - secure: YH0AqP/y2L3+YkHNezAOfBNMB5QkeEYE3z5NV5k7gxqaEPEklQeMrSHLZzN1TuSyms/RuiQ6Zj0QA9D2ZxioTxTqGUQbh5c+Ia5n5GTIJZYg24uVXPS1w6uFQSyVNIZE6tJGpgf0RHzeGtejRW7Q9Ppr6e55TBnBc53fGTqJyPs=
  email: roboptim@googlegroups.com
branches:
  only:
  - master
  - dev
  - debian
  - travis
  - coverity_scan
script:
  - export CMAKE_ADDITIONAL_OPTIONS="-DSTORAGE_ORDER=${ROBOPTIM_STORAGE_ORDER:-ColMajor}"
  - if [ "${COVERITY_SCAN_BRANCH}" != "1" ]; then ./.travis/run build; fi
after_success:
  - ./.travis/run after_success
  - codecov --gcov-root=/tmp/_ci/build
after_failure: ./.travis/run after_failure
before_install:
  - pip install --user codecov
  - ./.travis/run  before_install
  - ./.travis/dependencies/eigen-3.2

matrix:
  allow_failures:
    - compiler: clang
    - os: osx
    - env: COVERITY_SCAN_BRANCH=1
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      env: ROBOPTIM_STORAGE_ORDER=ColMajor
    - os: linux
      dist: trusty
      compiler: gcc
      env: ROBOPTIM_STORAGE_ORDER=RowMajor
    - os: linux
      dist: trusty
      compiler: clang
    - os: linux
      dist: precise
      compiler: gcc
    - os: linux
      dist: precise
      compiler: clang
    - os: osx
      compiler: clang
    - os: osx
      compiler: gcc

addons:
  coverity_scan:
    project:
      name: "roboptim/roboptim-core"
      description: "Build submitted via Travis CI"
    notification_email: roboptim@googlegroups.com
    build_command_prepend: ". .travis/common.sh && mkdir coverity && cd coverity && cmake .."
    build_command: "make"
    branch_pattern: coverity_scan
