language: cpp
compiler:
  - gcc
  - clang
env:
  global:
    - secure: "Qu8mVoUePFsfwAIkE4D6wvN6TlkBjSw/Ct5NZX7xab8NgudhYGHy9dlOrky1NsO7lEa2Ulf/toXroMNNfiIyn3HmLuUN2VsMv9dZ7mA7TdBEUdKKtWqMvsRLFFeeb/8+aWDfzPvck/zeUIRodE7DSc46xR74SyRx24uz+MgfMKQ="
    - secure: "Slm+HqRT+Vy0SG7E9gEShuHvNz6XWRUmBhVBLVJEaYy/0Lo2qp4OjFEWDjiJwFIiXstW2Wclds4SuewAn3Tc4x7dsY+5uaMCX7S/HPzsBCjLXUwjKasUqEGaVTIYmtFJm57hOkz6K2SLUUV4intkMiwtCiq/R0xe92QTTKkHyfo="
    - secure: "F9mibfsT3Ezk0RRsgOHy8RUO82H05REGmJKLDKdHiHE3toxykQX64oNBB8txjHoi+UF0H1Gwmk4oB/pNeILtyHdSuB7hB1Muod9wspOuKrzO7SMTGdjpPw7nDjQEmtfrZFhXEGb/3xm66uSGojhwe0RJF5mOzyfno+G8SIJyos4="
    - secure: "ZKC2yAvUcDb2nyrZQNqpLgEbi2pYFSKDn/+xIj9ZH+5nkn6iA5RT4AunK13qxuBkjIr2HJcUBtMFvk/mfpvpWynX+v9i3OhpVZCbkmcjQrATjiUcG6r95oEcex7NAM5uKd/41CqV/0fzTPc3uJgPozDJlt0wsBmCEarHiRNAoo0="
    - APT_DEPENDENCIES="doxygen doxygen-latex libltdl-dev libboost-all-dev liblog4cxx10-dev"
    - HOMEBREW_DEPENDENCIES="doxygen libtool boost log4cxx"
    - GIT_DEPENDENCIES=""
    - GH_REPO=roboptim/roboptim-core
    - DEBSIGN_KEYID=5AE5CD75
    - PPA_URI="roboptim/ppa"
    - LCOV_IGNORE_RULES="*tests*"
notifications:
  hipchat:
    rooms:
      - secure: YH0AqP/y2L3+YkHNezAOfBNMB5QkeEYE3z5NV5k7gxqaEPEklQeMrSHLZzN1TuSyms/RuiQ6Zj0QA9D2ZxioTxTqGUQbh5c+Ia5n5GTIJZYg24uVXPS1w6uFQSyVNIZE6tJGpgf0RHzeGtejRW7Q9Ppr6e55TBnBc53fGTqJyPs=
  email: roboptim@googlegroups.com
branches:
  only:
  - master
  - debian
  - travis
script: ./.travis/run build
after_success: ./.travis/run after_success
after_failure: ./.travis/run after_failure
before_install:
  - ./.travis/run  before_install
  - ./.travis/dependencies/eigen-3.2.0
matrix:
  allow_failures:
    - compiler: clang
    - os: osx
os:
  - linux
  - osx
